language: python
dist: xenial
addons:
  apt:
    packages:
      - python-setuptools
      - libwebp-dev
jobs:
  include:
    - stage: test
      python: "3.6"
    - stage: test
      python: "3.7"
    - stage: test
      python: "3.8"
    - stage: release
      python: "3.7"
      script: skip
      deploy:
        server: https://pypi.org/
        provider: pypi
        user: __token__
        password: $PYPI_PASS
        skip_existing: true
        on:
          tags: true
cache: pip
#before_install:
#  - echo $TRAVIS_PYTHON_VERSION
install:
  - pip install -U coverage setuptools pyinstaller mypy
  - pip install -r requirements.txt
script:
  - mypy manga_py  # check syntax
  - coverage run run_tests.py
stages:
  - name: test
  - name: release
    if: tag IS present
#    if: branch = master and tag IS present
