language: python
dist: xenial
#addons:
#  artifacts: true
addons:
  apt:
    packages:
      - python-setuptools
      - libwebp-dev
jobs:
  include:
    - stage: test
      python: "3.6"
    - stage: test
      python: "3.7"
    - stage: test
      python: "3.8"
    - stage: release
      python: "3.7"
      script: skip
      deploy:
        provider: pypi
        user: __token__
        password: $PYPI_KEY
        skip_existing: true
    - stage: master
      script: echo "master"
    - stage: tag
      script: echo "tag"
cache: pip
before_install:
  - echo $TRAVIS_PYTHON_VERSION
install:
  - pip install -U coverage setuptools pyinstaller mypy
  - pip install -r requirements.txt
script:
  - mypy manga_py  # check syntax
  - coverage run run_tests.py
stages:
  - name: test
  - name: release
    if: branch = master and tag IS present
  - name: master
    if: branch = master
  - name: tag
    if: tag IS present
