language: python
dist: xenial
addons:
  apt:
    packages:
    - python-setuptools
    - libwebp-dev
jobs:
  include:
  - stage: test
    python: '3.6'
  - stage: test
    python: '3.7'
  - stage: test
    python: '3.8'
  - stage: release
    python: '3.7'
    script: skip
    deploy:
      provider: pypi
      user: __token__
      password:
        secure: moVUFIcfmRTthk5ItNw1DC+1hwUbv7aN8AQWyfPo3hUk5llna9H8A5faWRRSmsb1YZmyo2YT7Cfp+ks59eeuV+zsgvwKRuA8KlTAoxBufQcyTWVq6U22Hsmvjuw9bCqwY9aY6fsMkwlf5FZCZGskzYH+8u8VIOYExrHFkkAtcv7cFVjBHmzFCImi0SHF8BRwV3LBFvIQPeDHuG82UL2+q4FdvFUiYb5EVlWGBPBP5oUrCykTRxqCaPfojyl2EXWE5/hpof3hNXNW5evAkYo9imGi8tPfXUxkAY1h0DFtdIZESnm0CCbsvH3AT7kLldFyFd0Ws5i+vxl7ECHn6xm1RIqfTFedde5WkAz67xNL/hE/6cAvmFITxGJhECLUPRJUv9XR20WRr4w1EXRrAEemzZaJRmUqmfsfNJ4UGXa40SlzkpBTFDusytKp4PZW0HMzyBsBDtAiL6L40+dR3LeOVV2Mkbj7KRpYgXeHZS39mmVWY7DBnT3FWlBw1RQpC6p7Po/xuKVwek/Zoqj+X9fQGOJ/hqUVbXLGEHWpUvIGrQ/SpjvXUSMK1Ix0snCDU39GdA0qs9+lkZ0Am1jfy0SY1cwR1I//XwPr3DapYcaRRTAvjudgVjHMxkhORsPzNSI1blRnDa7HuSShO/Ajd5pGdW272C9fS5llkr9U0x3CuNI=
      skip_existing: true
      on:
        tags: true
cache: pip
install:
- pip install -U coverage setuptools pyinstaller mypy
- pip install -r requirements.txt
script:
- mypy manga_py
- coverage run run_tests.py
stages:
- name: test
- name: release
  if: tag IS present